### ISSUE TITLE
Cannot install contributed modules that do not have an official release.

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/tugboat-demos#1] opened 2021-01-27 08:35 UTC
Since https://github.com/backdrop/backdrop-issues/issues/4914 was raised, and https://github.com/backdrop-contrib/ckeditor_addon was mentioned as an alternative, I thought I'd give it a go in a demo sandbox, instead of setting it up on my local. So I've:

- navigated to https://backdropcms.org/demo and span up a demo sandbox
- once the sandbox span up, I navigated to `admin/modules/install`
- clicked on the "Manual installation" link (`admin/installer/manual`)
- expanded the "HideInstall from a URL" fieldset
- pasted `https://github.com/backdrop-contrib/ckeditor_addon/archive/master.zip` into the URL field
- clicked "Install"

...I got redirected to `core/authorize.php`, with this error shown:

![image](https://user-images.githubusercontent.com/2423362/105964788-5c49e780-608b-11eb-922a-b01d0b2719e1.png)

**Comment by ghost** [comment] 2021-01-27 08:56
This sounds like a duplicate of https://github.com/backdrop/backdrop-issues/issues/3008 to me...

**Comment by ghost** [comment] 2021-01-27 09:43
I was able to replicate the problem by setting up a local site as per: https://github.com/backdrop/backdrop-issues/issues/3008#issuecomment-765897332 then using your steps above. Got the same error message in the screenshot above.

I therefore think this is indeed a version of that core bug, so closing as a duplicate.

**Closed as completed by ghost** 2021-01-27 09:43 UTC
Labels: duplicate
